apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: kaoto-operator-integrator-role
rules:
- apiGroups:
  - camel.apache.org
  resources:
  - kameletbindings
  - integrations
  - kamelets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
    - ""
  resources:
    - pods
    - pods/log
  verbs:
    - get
    - watch
    - list
