/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	designerv1alpha1 "github.com/kaotoIO/kaoto-operator/api/designer/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// KaotoLister helps list Kaotoes.
// All objects returned here must be treated as read-only.
type KaotoLister interface {
	// List lists all Kaotoes in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*designerv1alpha1.Kaoto, err error)
	// Kaotoes returns an object that can list and get Kaotoes.
	Kaotoes(namespace string) KaotoNamespaceLister
	KaotoListerExpansion
}

// kaotoLister implements the KaotoLister interface.
type kaotoLister struct {
	listers.ResourceIndexer[*designerv1alpha1.Kaoto]
}

// NewKaotoLister returns a new KaotoLister.
func NewKaotoLister(indexer cache.Indexer) KaotoLister {
	return &kaotoLister{listers.New[*designerv1alpha1.Kaoto](indexer, designerv1alpha1.Resource("kaoto"))}
}

// Kaotoes returns an object that can list and get Kaotoes.
func (s *kaotoLister) Kaotoes(namespace string) KaotoNamespaceLister {
	return kaotoNamespaceLister{listers.NewNamespaced[*designerv1alpha1.Kaoto](s.ResourceIndexer, namespace)}
}

// KaotoNamespaceLister helps list and get Kaotoes.
// All objects returned here must be treated as read-only.
type KaotoNamespaceLister interface {
	// List lists all Kaotoes in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*designerv1alpha1.Kaoto, err error)
	// Get retrieves the Kaoto from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*designerv1alpha1.Kaoto, error)
	KaotoNamespaceListerExpansion
}

// kaotoNamespaceLister implements the KaotoNamespaceLister
// interface.
type kaotoNamespaceLister struct {
	listers.ResourceIndexer[*designerv1alpha1.Kaoto]
}
