# permissions for end users to view kaotoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kaoto-viewer-role
rules:
- apiGroups:
  - kaoto.io
  resources:
  - kaotoes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kaoto.io
  resources:
  - kaotoes/status
  verbs:
  - get
