# permissions for end users to edit kaotoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kaoto-editor-role
rules:
- apiGroups:
  - kaoto.io
  resources:
  - kaotoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kaoto.io
  resources:
  - kaotoes/status
  verbs:
  - get
