/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	designerv1alpha1 "github.com/kaotoIO/kaoto-operator/api/designer/v1alpha1"
	versioned "github.com/kaotoIO/kaoto-operator/pkg/client/kaoto/clientset/versioned"
	internalinterfaces "github.com/kaotoIO/kaoto-operator/pkg/client/kaoto/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/kaotoIO/kaoto-operator/pkg/client/kaoto/listers/designer/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// KaotoInformer provides access to a shared informer and lister for
// Kaotoes.
type KaotoInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.KaotoLister
}

type kaotoInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewKaotoInformer constructs a new informer for Kaoto type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewKaotoInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredKaotoInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredKaotoInformer constructs a new informer for Kaoto type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredKaotoInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DesignerV1alpha1().Kaotoes(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DesignerV1alpha1().Kaotoes(namespace).Watch(context.TODO(), options)
			},
		},
		&designerv1alpha1.Kaoto{},
		resyncPeriod,
		indexers,
	)
}

func (f *kaotoInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredKaotoInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *kaotoInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&designerv1alpha1.Kaoto{}, f.defaultInformer)
}

func (f *kaotoInformer) Lister() v1alpha1.KaotoLister {
	return v1alpha1.NewKaotoLister(f.Informer().GetIndexer())
}
