/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	designerv1alpha1 "github.com/kaotoIO/kaoto-operator/api/designer/v1alpha1"
	applyconfigurationdesignerv1alpha1 "github.com/kaotoIO/kaoto-operator/pkg/client/kaoto/applyconfiguration/designer/v1alpha1"
	scheme "github.com/kaotoIO/kaoto-operator/pkg/client/kaoto/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// KaotoesGetter has a method to return a KaotoInterface.
// A group's client should implement this interface.
type KaotoesGetter interface {
	Kaotoes(namespace string) KaotoInterface
}

// KaotoInterface has methods to work with Kaoto resources.
type KaotoInterface interface {
	Create(ctx context.Context, kaoto *designerv1alpha1.Kaoto, opts v1.CreateOptions) (*designerv1alpha1.Kaoto, error)
	Update(ctx context.Context, kaoto *designerv1alpha1.Kaoto, opts v1.UpdateOptions) (*designerv1alpha1.Kaoto, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, kaoto *designerv1alpha1.Kaoto, opts v1.UpdateOptions) (*designerv1alpha1.Kaoto, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*designerv1alpha1.Kaoto, error)
	List(ctx context.Context, opts v1.ListOptions) (*designerv1alpha1.KaotoList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *designerv1alpha1.Kaoto, err error)
	Apply(ctx context.Context, kaoto *applyconfigurationdesignerv1alpha1.KaotoApplyConfiguration, opts v1.ApplyOptions) (result *designerv1alpha1.Kaoto, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, kaoto *applyconfigurationdesignerv1alpha1.KaotoApplyConfiguration, opts v1.ApplyOptions) (result *designerv1alpha1.Kaoto, err error)
	KaotoExpansion
}

// kaotoes implements KaotoInterface
type kaotoes struct {
	*gentype.ClientWithListAndApply[*designerv1alpha1.Kaoto, *designerv1alpha1.KaotoList, *applyconfigurationdesignerv1alpha1.KaotoApplyConfiguration]
}

// newKaotoes returns a Kaotoes
func newKaotoes(c *DesignerV1alpha1Client, namespace string) *kaotoes {
	return &kaotoes{
		gentype.NewClientWithListAndApply[*designerv1alpha1.Kaoto, *designerv1alpha1.KaotoList, *applyconfigurationdesignerv1alpha1.KaotoApplyConfiguration](
			"kaotoes",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *designerv1alpha1.Kaoto { return &designerv1alpha1.Kaoto{} },
			func() *designerv1alpha1.KaotoList { return &designerv1alpha1.KaotoList{} },
		),
	}
}
