/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	json "encoding/json"
	"fmt"
	"time"

	v1alpha1 "github.com/kaotoIO/kaoto-operator/apis/designer/v1alpha1"
	designerv1alpha1 "github.com/kaotoIO/kaoto-operator/pkg/client/kaoto/applyconfiguration/designer/v1alpha1"
	scheme "github.com/kaotoIO/kaoto-operator/pkg/client/kaoto/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// KaotoesGetter has a method to return a KaotoInterface.
// A group's client should implement this interface.
type KaotoesGetter interface {
	Kaotoes(namespace string) KaotoInterface
}

// KaotoInterface has methods to work with Kaoto resources.
type KaotoInterface interface {
	Create(ctx context.Context, kaoto *v1alpha1.Kaoto, opts v1.CreateOptions) (*v1alpha1.Kaoto, error)
	Update(ctx context.Context, kaoto *v1alpha1.Kaoto, opts v1.UpdateOptions) (*v1alpha1.Kaoto, error)
	UpdateStatus(ctx context.Context, kaoto *v1alpha1.Kaoto, opts v1.UpdateOptions) (*v1alpha1.Kaoto, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.Kaoto, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.KaotoList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Kaoto, err error)
	Apply(ctx context.Context, kaoto *designerv1alpha1.KaotoApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.Kaoto, err error)
	ApplyStatus(ctx context.Context, kaoto *designerv1alpha1.KaotoApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.Kaoto, err error)
	KaotoExpansion
}

// kaotoes implements KaotoInterface
type kaotoes struct {
	client rest.Interface
	ns     string
}

// newKaotoes returns a Kaotoes
func newKaotoes(c *DesignerV1alpha1Client, namespace string) *kaotoes {
	return &kaotoes{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the kaoto, and returns the corresponding kaoto object, and an error if there is any.
func (c *kaotoes) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Kaoto, err error) {
	result = &v1alpha1.Kaoto{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("kaotoes").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Kaotoes that match those selectors.
func (c *kaotoes) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.KaotoList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.KaotoList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("kaotoes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested kaotoes.
func (c *kaotoes) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("kaotoes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a kaoto and creates it.  Returns the server's representation of the kaoto, and an error, if there is any.
func (c *kaotoes) Create(ctx context.Context, kaoto *v1alpha1.Kaoto, opts v1.CreateOptions) (result *v1alpha1.Kaoto, err error) {
	result = &v1alpha1.Kaoto{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("kaotoes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(kaoto).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a kaoto and updates it. Returns the server's representation of the kaoto, and an error, if there is any.
func (c *kaotoes) Update(ctx context.Context, kaoto *v1alpha1.Kaoto, opts v1.UpdateOptions) (result *v1alpha1.Kaoto, err error) {
	result = &v1alpha1.Kaoto{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("kaotoes").
		Name(kaoto.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(kaoto).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *kaotoes) UpdateStatus(ctx context.Context, kaoto *v1alpha1.Kaoto, opts v1.UpdateOptions) (result *v1alpha1.Kaoto, err error) {
	result = &v1alpha1.Kaoto{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("kaotoes").
		Name(kaoto.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(kaoto).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the kaoto and deletes it. Returns an error if one occurs.
func (c *kaotoes) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("kaotoes").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *kaotoes) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("kaotoes").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched kaoto.
func (c *kaotoes) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Kaoto, err error) {
	result = &v1alpha1.Kaoto{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("kaotoes").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// Apply takes the given apply declarative configuration, applies it and returns the applied kaoto.
func (c *kaotoes) Apply(ctx context.Context, kaoto *designerv1alpha1.KaotoApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.Kaoto, err error) {
	if kaoto == nil {
		return nil, fmt.Errorf("kaoto provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(kaoto)
	if err != nil {
		return nil, err
	}
	name := kaoto.Name
	if name == nil {
		return nil, fmt.Errorf("kaoto.Name must be provided to Apply")
	}
	result = &v1alpha1.Kaoto{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("kaotoes").
		Name(*name).
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *kaotoes) ApplyStatus(ctx context.Context, kaoto *designerv1alpha1.KaotoApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.Kaoto, err error) {
	if kaoto == nil {
		return nil, fmt.Errorf("kaoto provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(kaoto)
	if err != nil {
		return nil, err
	}

	name := kaoto.Name
	if name == nil {
		return nil, fmt.Errorf("kaoto.Name must be provided to Apply")
	}

	result = &v1alpha1.Kaoto{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("kaotoes").
		Name(*name).
		SubResource("status").
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
