# These resources constitute the fully configured set of manifests
# used to generate the 'manifests/' directory in a bundle.
resources:
- bases/kaoto-operator.clusterserviceversion.yaml
- ../rbac/backend
- ../default
- ../samples
- ../scorecard
