name: Build Main

on:
  push:
    branches:
    - main
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  e2e:
    uses: ./.github/workflows/e2e.yml
    with:
      standalone-version: "quay.io/kaotoio/standalone:stable-jvm"
  deploy:
    needs:
      - e2e
    uses: ./.github/workflows/build-and-push.yml
    with:
      version: "${{ github.ref_name }}-${{ github.sha }}"
      standalone-version: "quay.io/kaotoio/standalone:stable-jvm"
      olm: false
      tag: main
      latest: true
    secrets:
      registry: "quay.io"
      registry-username: ${{ secrets.QUAY_USERNAME }}
      registry-password: ${{ secrets.QUAY_PASSWORD }}