name: Build And Push

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
    secrets:
      registry:
        required: true
      registry-username:
        required: true
      registry-password:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Set up Go"
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: "Build"
        run: make build
      - name: "Test"
        run: make test
  publish:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Set up Go"
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: "Login to Container registry"
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.registry }}
          username: ${{ secrets.registry-username }}
          password: ${{ secrets.registry-password }}      
      - name: Set versions
        run: |
          export INPUT_VERSION="${{ inputs.version }}"
          export C_VERSION="${INPUT_VERSION#v}"

          echo "VERSION=${C_VERSION}" >> $GITHUB_ENV
          echo "IMG_VERSION=${C_VERSION}" >> $GITHUB_ENV
      - name: "Build the Container image"
        run: |
          make docker-build
      - name: "Push the Container image"
        run: |
          make docker-push
      - name: "Build the OLM bundle"
        run: |
          make bundle
      - name: "Build the OLM bundle image"
        run: |
          make bundle-build
      - name: "Push the OLM bundle image"
        run: |
          make bundle-push
      - name: "Make the catalog image"
        run: |
          make catalog-build
      - name: "Push the catalog image"
        run: |
          make catalog-push
