name: Build Tag

on:
  push:
    tags:
      - "v*"

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:  
  setup:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set-version.outputs.version }}
    steps:
      - name: "Set Version"
        id: "set-version"
        run: |
          export C_VERSION="${GITHUB_REF_NAME#v}"

          echo "version=${C_VERSION}" >> "$GITHUB_OUTPUT"
  build:
    uses: ./.github/workflows/build-and-push.yml
    needs:
      - setup
    with:
      version: "${{ needs.setup.outputs.version }}"
      olm: true
    secrets:
      registry: "quay.io"
      registry-username: ${{ secrets.QUAY_USERNAME }}
      registry-password: ${{ secrets.QUAY_PASSWORD }}
