name: Publish Release
on:
  push:
    tags:
      - "v*"

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  release:
    uses: ./.github/workflows/build-and-push.yml
    with:
      version: "${{ github.ref_name }}"
      standalone-image: "quay.io/kaotoio/standalone:stable-jvm"
      olm: false
      tag: "${{ github.ref_name }}"
      latest: false
    secrets:
      registry: "quay.io"
      registry-username: ${{ secrets.QUAY_USERNAME }}
      registry-password: ${{ secrets.QUAY_PASSWORD }}

