name: Build PR

on:
  pull_request:
    branches:
    - main
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Set up Go"
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          check-latest: true
      - name: "Build"
        run: make build
      - name: "Test"
        run: make test
  e2e:
    uses: ./.github/workflows/e2e.yml
    needs:
      - build
