name: E2E

on:
  workflow_call:
    inputs:
      standalone-image:
        required: true
        type: string

jobs:
  images:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.publish.outputs.image }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Set up Go"
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
          check-latest: true
      - name: "Publish Image"
        id: "publish"
        env:
          KAOTO_STANDALONE_IMAGE: ${{ inputs.standalone-image }}
        run: |
          export UUID=$(uuidgen)
          export IMG="ttl.sh/${UUID}-${GITHUB_RUN_ID}-${GITHUB_RUN_NUMBER}:1h"
          
          echo $IMG
          echo "image=${IMG}" >> "$GITHUB_OUTPUT"
          
          make docker-build docker-push
  e2e:
    runs-on: ubuntu-latest
    needs:
      - images
    env:
      IMG: ${{needs.images.outputs.image}}
    strategy:
      matrix:
        kubernetes-version:
          - "1.27.3"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "SetUp Go"
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
          check-latest: true
      - name: 'SetUp KinD'
        uses: container-tools/kind-action@v2
        with:
          version: "v0.20.0"
          kubectl_version: v${{ matrix.kubernetes-version }}
          registry: false
          node_image: kindest/node:v${{ matrix.kubernetes-version }}
          config: test/e2e/kind.yaml
      - name: 'SetUp Kind Ingress'
        run: |
          kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml

          kubectl wait \
            --namespace=ingress-nginx \
            --for=condition=ready \
            pod \
            --selector=app.kubernetes.io/component=controller \
            --timeout=90s
      - name: "SetUp Kaoto Operator"
        run: |          
          make deploy/e2e
          
          kubectl wait \
            --namespace=kaoto-system \
            --for=condition=ready \
            pod \
            --selector=control-plane=kaoto-operator \
            --timeout=90s
      - name: "Run e2e"
        run: |
          make test/e2e
